"""Start and end dates

Revision ID: 50583ea22f36
Revises: e08ef71e4ceb
Create Date: 2023-12-06 11:01:40.277271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50583ea22f36'
down_revision = 'e08ef71e4ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('image')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
