"""Removed start and end dates

Revision ID: 5c398703ba75
Revises: 50583ea22f36
Create Date: 2023-12-06 11:13:52.363041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c398703ba75'
down_revision = '50583ea22f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_date', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
