"""Added phone_number column

Revision ID: 959e6d9954a6
Revises: 
Create Date: 2023-12-06 04:42:17.280435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '959e6d9954a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment_number', sa.String(length=20), nullable=False))
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.drop_column('apartment_number')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
